### PR TITLE
Code signing fix

### PR DESCRIPTION
**Pull request by notthatmj**
Removed a couple of "DevelopmentTeam = " lines from project.pbxproj which I think were the cause of our code signing woes.

### CODE REVIEW

**Comment by DavidSights** [comment]
Nice! No more code signing issues! Hopefully… 

David Seitz Jr
(312) 659-4670

**Comment by pablq** [comment]
Does this response work?

I've begun thinking about refactoring game logic out of view controller. 

Instead, I'll have the game hand the view controller event descriptions and choices. The vc will tell the game what choice was picked and the game will give the vc the next event/choices.

The game class will be fed an environment which consists of just data (no logic in environments... Just events/choices).

The game will expose methods to the vc to give it the information it needs and nothing more.

Please holler at me if you have any thoughts on this.

I won't write any code until I have figured out a clean system. All my changes will live in a new branch.

I think we also need to take a closer look at the audio aspect of the game. Mostly, we need make sure the audio is consistent throughout the experience - right now the first event isn't read and the last event gets read twice.

Maybe we can do away with manually reading the text, and instead indicate a new event with a sound effect.

Pablo

**Comment by notthatmj** [comment]
On Mon, Jul 13, 2015 at 3:43 PM, Pablo Philipps notifications@github.com
wrote:

> Instead, I'll have the game hand the view controller event descriptions
> and choices. The vc will tell the game what choice was picked and the game
> will give the vc the next event/choices.
> 
> The game class will be fed an environment which consists of just data (no
> logic in environments... Just events/choices).
> 
> The game will expose methods to the vc to give it the information it needs
> and nothing more.
> 
> I think this is the right idea.

--MJ

**Comment by DavidSights** [comment]
I like the idea of moving things out of the ViewController. That’s proper MVC design, and it’s something I’m a big fan of - I need to start making it second nature for myself. I also like the idea of sound effects! During our hackathon review, it was mentioned that we could add things like forrest sounds. Maybe the new sound that’s presented with each event could be the user’s queue that something new has happened. :-)

David Seitz Jr
(312) 659-4670

**Comment by pablq** [comment]
Yo I got pulled away this weekend for a job coding challenge. I'm looking forward to busting out Game class this week. It'll have public methods getInitialEvent, getnexteventgivenchoice, getScore, and whatever else you may need. the viewcontroller should only need to bother with setting up UI and relaying the user's choice to game.

Pablq

**Comment by DavidSights** [comment]
Sounds great, Pablo. I wish I had more time to dedicate to it now. Between job hunting, a contract iOS job, and working part-time, time is short for me. As soon as I do get some free time, I’d like to revisit it and clean up some code. Alternatively, if you feel at any point it’s ready to be submitted to the App Store, let me know and I’ll get that going! 

Best,

David Seitz Jr
(312) 659-4670

**Comment by pablq** [comment]
Needs to be done before submit:
- Make game code is solid (no crashes).
- build in portal events and polish mountain content.
- clean the audio experience a bit.

I will start with game code.

Event/choice format will stay the same for now.

Pablo

**Pull request merged**
